### PR TITLE
The Wild"er" Update

### PR DESCRIPTION
**Pull request by Robongio**

### CODE REVIEW

**Comment by KnoXy04** [comment]
Hey, I would like to help Alex's Mobs Mod and translate it to my native language (Catalan), is that possible?

**Comment by Robongio** [comment]
> Hey, I would like to help Alex's Mobs Mod and translate it to my native language (Catalan), is that possible?

Yes! You! Can!

**Comment by KnoXy04** [comment]
Yes thanks, add me at Discord: KnoXy#5800 .

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Robongio** [comment]
> Yes thanks, add me at Discord: KnoXy#5800 . Obtener Outlook para Android<https://aka.ms/ghei36>

Or you could just create json file with code name ca_es, and later submit it in your own pull request. I mean ... At least that's what I did.

**Pull request merged**
