### PR TITLE
More Modded Biome Tweaking

### PR DESCRIPTION
**Pull request by BugmanBugman**
Fixed a typo, and added modded biome block support in the json's so the mobs will be able to properly spawn in those biomes

### CODE REVIEW

**Comment by Alex-the-666** [comment]
you cannot put non existant blocks in a block tag if the mod is not installed. the changes proposed would make it so some mobs would not spawn at all, and likely crash the game, without byg installed.

**Comment by BugmanBugman** [comment]
ah I see, is there any work around to get the nether mobs spawning in? I believe the #forge:netherrack tag should be good enough for most mobs since byg blacks use that tag, but for biomes o plenty’s visceral heap biome, it doesn’t have any tags for its blocks.

**Comment by Alex-the-666** [comment]
yeah, that woud work if it was changed. as for BoP blocks not being tagged, you could always use a datapack to add them to our spawn lists.

**Comment by BugmanBugman** [comment]
Superseded by #241

**Pull request closed without merging**
