### PR TITLE
Fix Leafcutter Ants forgetting their home pos after harvesting a leaf

### LINKED ISSUE #1961: Leafcutter ant
The leafcutter ants don't go back to the nest as soon as they get a leaf, instead they wander far away from the nest. This also happens with the Leafcutter ant pupa.

### PR DESCRIPTION
**Pull request by Drullkus**
Leafcutter Ants no longer forget their home pos after harvesting a leaf. Fixes #1961

### CODE REVIEW

**Comment by LeafcuttingAnt** [comment]
I don't get it, what does this mean? Is this a fix i can download? Or are you asking alex to implement this?

**Comment by Enderteck** [comment]
This is a pull request which means it asks to change code in the mod.
If the mods devs/maintainers approve it, it will become part of the mod's code. It will probably fix that issue but it isn't yet implemented unfortunately.

**Comment by Enderteck** [comment]
I just compiled it if you can't wait: (Neoforge 1.20.1)

[alexsmobs-1.22.7.jar.zip](https://github.com/AlexModGuy/AlexsMobs/files/14471515/alexsmobs-1.22.7.jar.zip)

Just rename it to remove the .zip extension and put it in your mod folder.

**Comment by Enderteck** [comment]
Works like a charm !

Screenshot1
Screenshot2

**Pull request merged**
